name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  service_a:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build service_a
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/service_a.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  service_b:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build service_b
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/service_b.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
